#
# see makefile.html for instuctions.
#

NAME=ccdump
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\ccdump.obj

USE_DEFAULTLIB=1
LIBS=krbcc32.lib
LIB_PATHS=..\krbcc32\$(O)

INCLUDES=..\include

NO_PLACE=1
