#
# see makefile.html for instuctions.
#

NAME=aklog
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\aklog.obj \
	$(O)\linked_list.obj \
	$(O)\pioctl.obj

USE_DEFAULTLIB=1
C_DEFINE=-DAKLOG_KRB5

LIBS=krbv4w32.lib afscompat.lib wsock32.lib krb5_32.lib
LIB_PATHS=..\..\..\target\lib\$(T)
INCLUDES=..\krb4\include;..\..\util\lib\afscompat\inc;..\krb5\src\include

USE_LIBC_DLL=1
