#
# see makefile.html for instuctions.
#

NAME=klist
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\klist.obj

LIBS=..\..\krbdll\$(O)\krbv4w32.lib
INCLUDES=..;..\..\..\include

USE_DEFAULTLIB=1
NO_PLACE=1
