#
# see makefile.html for instuctions.
#

NAME=kinit
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\kinit.obj

LIBS=..\$(O)\kuser.lib advapi32.lib
INCLUDES=..;..\..\krb5\src\include;..\..\krb4\include;\
	$(PISMERE)\athena\util\loadfuncs;..\..\leash\include

USE_DEFAULTLIB=1
RES=$(O)\kinit.res
