#
# see makefile.html for instuctions.
#

NAME=kinit
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\kinit.obj

LIBS=..\$(O)\kuser.lib advapi32.lib \
	$(PISMERE)\athena\util\lib\getopt\$(O)\getopt.lib
INCLUDES=..;..\..\krb5\src\include;..\..\krb4\include;\
	$(PISMERE)\athena\util\loadfuncs;$(PISMERE)\athena\util\lib\getopt;\
	..\..\leash\include

USE_DEFAULTLIB=1
RES=$(O)\kinit.res

C_DEFINE=-DKRB5_KRB4_COMPAT -DGETOPT_LONG -DKINIT_DEFAULT_BOTH
