#define com_err pcom_err
#define krb5_string_to_deltat pkrb5_string_to_deltat
#define krb5_string_to_timestamp pkrb5_string_to_timestamp
#define krb5_read_password pkrb5_read_password
#define krb5_timestamp_to_sfstring pkrb5_timestamp_to_sfstring
