/*
 * lib/gssapi/generic/gssapi_err_generic.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_ggss_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"No @ in SERVICE-NAME name string",
	"STRING-UID-NAME contains nondigits",
	"UID does not resolve to username",
	"Validation error",
	"Couldn't allocate gss_buffer_t data",
	"Message context invalid",
	"Buffer is the wrong size",
	"Credential usage type is unknown",
	"Unknown quality of protection specified",
	"Local host name could not be determined",
	"Hostname in SERVICE-NAME string could not be canonicalized",
	"Mechanism is incorrect",
	"Token header is malformed or corrupt",
	"Packet was replayed in wrong direction",
	"Token is missing data",
	"Token was reflected",
	"Received token ID does not match expected token ID",
    0
};

#include <com_err.h>

const struct error_table et_ggss_error_table = { text, -2045022976L, 17 };

#if !defined(_WIN32)
void initialize_ggss_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_ggss_error_table);
}
#endif
