#
# see makefile.html for instuctions.
#

NAME=wshload
TARGETTYPE=LIB
TARGETSS=console

OBJS = \
	$(O)\wshload.obj

USE_DEFAULTLIB=1

INCLUDES=..\include

C_DEFINE=-DWINDOWS -D_WINDOWS
