DIRS=util\getdomainname util\guiwrap util\loadfuncs util\lib\delaydlls util\lib\getopt vs \
	wshelper util\lib\afscompat auth util\lib\about \
	front\frontrpc util zephyr print moira service afs\extra afs-3.6 openafs
OPTDIRS=util\guiwrap vs util\lib\afscompat util\lib\about \
    front\frontrpc util zephyr print moira service afs\extra afs-3.6 openafs
