#
# see makefile.html for instuctions.
#

NAME=k4test
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\k4test.obj

LIBS=..\krbdll\$(O)\krbv4w32.lib
INCLUDES=..\..\include

USE_DEFAULTLIB=1
# NO_PLACE=1
