/*
 * util/profile/prof_err.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_prof_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"Profile version 0.0",
	"Bad magic value in profile_node",
	"Profile section not found",
	"Profile relation not found",
		"Attempt to add a relation to node which is not a section",
		"A profile section header has a non-zero value",
	"Bad linked list in profile structures",
	"Bad group level in profile strctures",
		"Bad parent pointer in profile strctures",
	"Bad magic value in profile iterator",
	"Can't set value on section node",
	"Invalid argument passed to profile library",
	"Attempt to modify read-only profile",
	"Profile section header not at top level",
	"Syntax error in profile section header",
	"Syntax error in profile relation",
	"Extra closing brace in profile",
	"Missing open brace in profile",
	"Bad magic value in profile_t",
	"Bad magic value in profile_section_t",
		"Iteration through all top level section not supported",
	"Invalid profile_section object",
	"No more sections",
	"Bad nameset passed to query routine",
	"No profile file open",
	"Bad magic value in profile_file_t",
	"Couldn't open profile file",
	"Section already exists",
	"Invalid boolean value",
	"Invalid integer value",
	"Bad magic value in profile_file_data_t",
    0
};

#include <com_err.h>

const struct error_table et_prof_error_table = { text, -1429577728L, 31 };

#if !defined(_WIN32)
void initialize_prof_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_prof_error_table);
}
#endif
