#
# see makefile.html for instuctions.
#

NAME=cctest
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\cctest.obj

USE_DEFAULTLIB=1
USE_LIBC_DLL=1
DEP_LIBS=..\dll\$(O)\krbcc32.lib ..\lib\$(O)\ccutil.lib
LIBS=$(DEP_LIBS) user32.lib advapi32.lib 
INCLUDES=..\inc

C_DEFINE=-DWIN32_LEAN_AND_MEAN
