/*
 * lib/gssapi/krb5/gssapi_err_krb5.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_k5g_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"Principal in credential cache does not match desired name",
	"No principal in keytab matches desired name",
	"Credential cache has no TGT",
	"Authenticator has no subkey",
	"Context is already fully established",
	"Unknown signature type in token",
	"Invalid field length in token",
	"Attempt to use incomplete security context",
	"Bad magic number for krb5_gss_ctx_id_t",
	"Bad magic number for krb5_gss_cred_id_t",
	"Bad magic number for krb5_gss_enc_desc",
	"Sequence number in token is corrupt",
	"Credential cache is empty",
	"Acceptor and Initiator share no checksum types",
    0
};

#include <com_err.h>

const struct error_table et_k5g_error_table = { text, 39756032L, 14 };

#if !defined(_WIN32)
void initialize_k5g_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_k5g_error_table);
}
#endif
