/*
 * lib/krb4/kadm_err.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_kadm_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"$Header: /cvs/krbdev/krb5/src/lib/krb4/kadm_err.et,v 1.1 2002/11/27 03:09:34 tlyu Exp $",
	"Cannot fetch local realm",
	"Unable to fetch credentials",
	"Bad key supplied",
	"Can't encrypt data",
	"Cannot encode/decode authentication info",
	"Principal attemping change is in wrong realm",
	"Packet is too large",
	"Version number is incorrect",
	"Checksum does not match",
	"Unsealing private data failed",
	"Unsupported operation",
	"Could not find administrating host",
	"Administrating host name is unknown",
	"Could not find service name in services database",
	"Could not create socket",
	"Could not connect to server",
	"Could not fetch local socket address",
	"Could not fetch master key",
	"Could not verify master key",
	"Entry already exists in database",
	"Database store error",
	"Database read error",
	"Insufficient access to perform requested operation",
	"Data is available for return to client",
	"No such entry in the database",
	"Memory exhausted",
	"Could not fetch system hostname",
	"Could not bind port",
	"Length mismatch problem",
	"Illegal use of wildcard",
	"Database locked or in use",
	"Insecure password rejected",
	"Cleartext password and DES key did not match",
	"Invalid principal for change srvtab request",
	"Realm name too long",
    0
};

#include <com_err.h>

const struct error_table et_kadm_error_table = { text, -1783126272L, 36 };

#if !defined(_WIN32)
void initialize_kadm_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_kadm_error_table);
}
#endif
