TARGETTYPE=NONE

!ifdef NODEBUG
VCDBG=Release
!else
VCDBG=Debug
!endif

MAKECMD=$(MAKE) -$(MAKEFLAGS)

all::
	$(MAKECMD) all

clean::
	$(MAKECMD) clean

PLACE=src\librpc\obj\$(CPU)\$(VCDBG)\oncrpc.dll src\portmap\obj\$(CPU)\$(VCDBG)\portmap.exe