/*
 * lib/krb5/error_tables/asn1_err.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_asn1_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"ASN.1 failed call to system time library",
	"ASN.1 structure is missing a required field",
	"ASN.1 unexpected field number",
	"ASN.1 type numbers are inconsistent",
	"ASN.1 value too large",
	"ASN.1 encoding ended unexpectedly",
	"ASN.1 identifier doesn't match expected value",
	"ASN.1 length doesn't match expected value",
	"ASN.1 badly-formatted encoding",
	"ASN.1 parse error",
	"ASN.1 bad return from gmtime",
	"ASN.1 non-constructed indefinite encoding",
	"ASN.1 missing expected EOC",
    0
};

#include <com_err.h>

const struct error_table et_asn1_error_table = { text, 1859794432L, 13 };

#if !defined(_WIN32)
void initialize_asn1_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_asn1_error_table);
}
#endif
