/*
 * lib/krb5/error_tables/kdb5_err.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_kdb5_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"$Id: kdb5_err.et,v 5.21 2001/10/25 20:20:57 tlyu Exp $",
	"Entry already exists in database",
	"Database store error",
	"Database read error",
	"Insufficient access to perform requested operation",
	"No such entry in the database",
	"Illegal use of wildcard",
	"Database is locked or in use--try again later",
	"Database was modified during read",
	"Database record is incomplete or corrupted",
	"Attempt to lock database twice",
	"Attempt to unlock database when not locked",
	"Invalid kdb lock mode",
	"Database has not been initialized",
	"Database has already been initialized",
	"Bad direction for converting keys",
	"Cannot find master key record in database",
	"Master key does not match database",
	"Key size in database is invalid",
	"Cannot find/read stored master key",
	"Stored master key is corrupted",
	"Insufficient access to lock database",
	"Database format error",
	"Unsupported version in database entry",
	"Unsupported salt type",
	"Unsupported encryption type",
	"Bad database creation flags",
	"No matching key in entry having a permitted enctype",
	"No matching key in entry",
    0
};

#include <com_err.h>

const struct error_table et_kdb5_error_table = { text, -1780008448L, 29 };

#if !defined(_WIN32)
void initialize_kdb5_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_kdb5_error_table);
}
#endif
