/*
 * lib/krb5/error_tables/kv5m_err.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_kv5m_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"Kerberos V5 magic number table",
	"Bad magic number for krb5_principal structure",
	"Bad magic number for krb5_data structure",
	"Bad magic number for krb5_keyblock structure",
	"Bad magic number for krb5_checksum structure",
	"Bad magic number for krb5_encrypt_block structure",
	"Bad magic number for krb5_enc_data structure",
	"Bad magic number for krb5_cryptosystem_entry structure",
	"Bad magic number for krb5_cs_table_entry structure",
	"Bad magic number for krb5_checksum_entry structure",
	"Bad magic number for krb5_authdata structure",
	"Bad magic number for krb5_transited structure",
	"Bad magic number for krb5_enc_tkt_part structure",
	"Bad magic number for krb5_ticket structure",
	"Bad magic number for krb5_authenticator structure",
	"Bad magic number for krb5_tkt_authent structure",
	"Bad magic number for krb5_creds structure",
	"Bad magic number for krb5_last_req_entry structure",
	"Bad magic number for krb5_pa_data structure",
	"Bad magic number for krb5_kdc_req structure",
	"Bad magic number for krb5_enc_kdc_rep_part structure",
	"Bad magic number for krb5_kdc_rep structure",
	"Bad magic number for krb5_error structure",
	"Bad magic number for krb5_ap_req structure",
	"Bad magic number for krb5_ap_rep structure",
	"Bad magic number for krb5_ap_rep_enc_part structure",
	"Bad magic number for krb5_response structure",
	"Bad magic number for krb5_safe structure",
	"Bad magic number for krb5_priv structure",
	"Bad magic number for krb5_priv_enc_part structure",
	"Bad magic number for krb5_cred structure",
	"Bad magic number for krb5_cred_info structure",
	"Bad magic number for krb5_cred_enc_part structure",
	"Bad magic number for krb5_pwd_data structure",
	"Bad magic number for krb5_address structure",
	"Bad magic number for krb5_keytab_entry structure",
	"Bad magic number for krb5_context structure",
	"Bad magic number for krb5_os_context structure",
	"Bad magic number for krb5_alt_method structure",
	"Bad magic number for krb5_etype_info_entry structure",
	"Bad magic number for krb5_db_context structure",
	"Bad magic number for krb5_auth_context structure",
	"Bad magic number for krb5_keytab structure",
	"Bad magic number for krb5_rcache structure",
	"Bad magic number for krb5_ccache structure",
	"Bad magic number for krb5_preauth_ops",
	"Bad magic number for krb5_sam_challenge",
	"Bad magic number for krb5_sam_challenge_2",
	"Bad magic number for krb5_sam_key",
	"Bad magic number for krb5_enc_sam_response_enc",
	"Bad magic number for krb5_enc_sam_response_enc",
	"Bad magic number for krb5_sam_response",
	"Bad magic number for krb5_sam_response 2",
	"Bad magic number for krb5_predicted_sam_response",
	"Bad magic number for passwd_phrase_element",
	"Bad magic number for GSSAPI OID",
	"Bad magic number for GSSAPI QUEUE",
    0
};

#include <com_err.h>

const struct error_table et_kv5m_error_table = { text, -1760647424L, 57 };

#if !defined(_WIN32)
void initialize_kv5m_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_kv5m_error_table);
}
#endif
