#
# see makefile.html for instuctions.
#

NAME=kinit
TARGETTYPE=EXE
TARGETSS=console

OBJS= \
	$(O)\kinit.obj

LIBS=..\..\krbdll\$(O)\krbv4w32.lib
INCLUDES=..;..\..\..\include

USE_DEFAULTLIB=1
NO_PLACE=1
